// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { EntitiesCreateEntityData, EntitiesCreateEntityResponse, EntitiesListEntitiesData, EntitiesListEntitiesResponse, EntitiesGetEntityData, EntitiesGetEntityResponse, EntitiesUpdateEntityData, EntitiesUpdateEntityResponse, EntitiesDeleteEntityData, EntitiesDeleteEntityResponse, OperationsHealthzResponse, OperationsReadyzResponse, OperationsVersionResponse } from './types.gen';

export class EntitiesService {
    /**
     * Create Entity
     * Create a new entity owned by the authenticated user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns EntityPublic Successful Response
     * @throws ApiError
     */
    public static createEntity(data: EntitiesCreateEntityData): CancelablePromise<EntitiesCreateEntityResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/entities/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Entities
     * List entities owned by the authenticated user with pagination.
     * @param data The data for the request.
     * @param data.offset
     * @param data.limit
     * @returns EntitiesPublic Successful Response
     * @throws ApiError
     */
    public static listEntities(data: EntitiesListEntitiesData = {}): CancelablePromise<EntitiesListEntitiesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/entities/',
            query: {
                offset: data.offset,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Entity
     * Retrieve a single entity by ID.
     * @param data The data for the request.
     * @param data.entityId
     * @returns EntityPublic Successful Response
     * @throws ApiError
     */
    public static getEntity(data: EntitiesGetEntityData): CancelablePromise<EntitiesGetEntityResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/entities/{entity_id}',
            path: {
                entity_id: data.entityId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Entity
     * Partially update an entity.
     * @param data The data for the request.
     * @param data.entityId
     * @param data.requestBody
     * @returns EntityPublic Successful Response
     * @throws ApiError
     */
    public static updateEntity(data: EntitiesUpdateEntityData): CancelablePromise<EntitiesUpdateEntityResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/entities/{entity_id}',
            path: {
                entity_id: data.entityId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Entity
     * Delete an entity.
     * @param data The data for the request.
     * @param data.entityId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteEntity(data: EntitiesDeleteEntityData): CancelablePromise<EntitiesDeleteEntityResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/entities/{entity_id}',
            path: {
                entity_id: data.entityId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class OperationsService {
    /**
     * Healthz
     * Liveness probe — returns 200 immediately with no dependency checks.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static healthz(): CancelablePromise<OperationsHealthzResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/healthz'
        });
    }
    
    /**
     * Readyz
     * Readiness probe — checks Supabase connectivity.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readyz(): CancelablePromise<OperationsReadyzResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/readyz'
        });
    }
    
    /**
     * Version
     * Build metadata from environment variables for gateway discoverability.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static version(): CancelablePromise<OperationsVersionResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/version'
        });
    }
}