// This file is auto-generated by @hey-api/openapi-ts

/**
 * Paginated collection of entities returned to API consumers.
 */
export type EntitiesPublic = {
    data: Array<EntityPublic>;
    count: number;
};

/**
 * Payload for creating a new entity.
 *
 * Inherits ``title`` (required) and ``description`` (optional) from
 * :class:`EntityBase`.
 */
export type EntityCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Full entity representation returned to API consumers.
 */
export type EntityPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Payload for partially updating an existing entity.
 *
 * Does NOT inherit :class:`EntityBase` so that every field is optional,
 * enabling true partial-update (PATCH) semantics.
 */
export type EntityUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type EntitiesCreateEntityData = {
    requestBody: EntityCreate;
};

export type EntitiesCreateEntityResponse = (EntityPublic);

export type EntitiesListEntitiesData = {
    limit?: number;
    offset?: number;
};

export type EntitiesListEntitiesResponse = (EntitiesPublic);

export type EntitiesGetEntityData = {
    entityId: string;
};

export type EntitiesGetEntityResponse = (EntityPublic);

export type EntitiesUpdateEntityData = {
    entityId: string;
    requestBody: EntityUpdate;
};

export type EntitiesUpdateEntityResponse = (EntityPublic);

export type EntitiesDeleteEntityData = {
    entityId: string;
};

export type EntitiesDeleteEntityResponse = (void);

export type OperationsHealthzResponse = ({
    [key: string]: (string);
});

export type OperationsReadyzResponse = (unknown);

export type OperationsVersionResponse = ({
    [key: string]: (string);
});